#!/usr/bin/env python

import sys
import os.path

file_path = "/mms5-layer1-service/src/main/resources/application.conf"
if not os.path.isfile(file_path):
    # open both files
    app_example = "/mms5-layer1-service/src/main/resources/application.conf.example"
    with open(app_example,'r') as firstfile, open(file_path,'w') as secondfile:
        # read content from first file
        for line in firstfile:
                 # append content to second file
                 secondfile.write(line)

