apiVersion: v1
data:
  MMS5_GRAPH_STORE_PROTOCOL_URL: https://quadstore/sparql/gsp/
  MMS5_LOAD_SERVICE_URL: http://mms5-storage-service.mms5.svc.cluster.local:8080/store
  MMS5_QUAD_STORE_URL: https://quadstore/sparql
  MMS5_QUERY_URL: https://quadstore/sparql
  MMS5_ROOT_CONTEXT: https://mms5.openmbee.org
  MMS5_SERVICE_ID: mms5-layer1-0
  MMS5_UPDATE_URL: https://quadstore/sparql
kind: ConfigMap
metadata:
  name: mms5-layer-1-config
  namespace: mms5
