version: '3.8'

services:

  openldap-server:
    image: bitnami/openldap:2.6.4
    hostname: openldap-server
    container_name: openldap-server
    ports:
      - 1389:1389
    environment:
      - LDAP_PORT_NUMBER=1389
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_USER_DC=users
      - LDAP_GROUP=group01
      - LDAP_PASSWORDS=password1,password2

  quad-store-server:
    image: ontotext/graphdb:10.3.0
    hostname: quad-server
    container_name: quad-server
    #command: --file=/tmp/mount/cluster.trig --update /ds
    #volumes:
    #  - ${PWD}/mount:/tmp/mount
    ports:
      - 7200:7200

  minio-server:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z.hotfix.15f13935a
    hostname: minio-server
    container_name: minio-server
    environment:
      - MINIO_ACCESS_KEY=admintest
      - MINIO_SECRET_KEY=admintest
    command: server /tmp/data
    ports:
      - 9000:9000

  auth-service:
    image: openmbee/mms5-auth-service:latest
    hostname: auth-service
    container_name: auth-service
    env_file:
      - ${PWD}/env/mms5-jwt.env
      - ${PWD}/env/mms5-auth.env
    depends_on:
      - openldap-server
      - quad-store-server
    ports:
      - 8082:8080

  store-service:
    image: openmbee/mms5-store-service:latest
    hostname: store-service
    container_name: store-service
    env_file:
      - ${PWD}/env/mms5-jwt.env
      - ${PWD}/env/mms5-store.env
    depends_on:
      - minio-server
    ports:
      - 8081:8080

  layer1-service:
    image: openmbee/mms5-layer1-service:develop-SNAPSHOT
    hostname: layer1-service
    container_name: layer1-service
    env_file:
      - ${PWD}/env/mms5-jwt.env
      - ${PWD}/env/mms5-layer1.env
    depends_on:
      - store-service
      - auth-service
      - quad-store-server
    ports:
      - 8080:8080

networks:
  default:
    name: mms5-test-network
    driver: bridge
