apiVersion: apps/v1
kind: Deployment
metadata:
  name: flexo-mms-auth-service
  namespace: flexo-mms
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-flexo-mms-flexo-mms-auth-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-flexo-mms-flexo-mms-auth-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: jwt-config
            optional: false
        - configMapRef:
            name: os-config
        - configMapRef:
            name: ldap-config
            optional: false
        image: openmbee/flexo-mms-auth-service:latest
        imagePullPolicy: Always
        name: flexo-mms-auth-service
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mnt/config/logback/
          name: logback-config-map
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          items:
          - key: logback.xml
            path: loggers-include.xml
          name: logback-config
          optional: false
        name: logback-config-map
