apiVersion: apps/v1
kind: Deployment
metadata:
  name: mms5-proxy-service
  namespace: mms5
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-mms5-mms5-proxy-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-mms5-mms5-proxy-service
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: mms5-proxy-conf
        image: nginx:1.23-alpine
        imagePullPolicy: Always
        name: mms5-proxy-service
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: proxy-config-map
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          items:
            - key: mms5.conf
              path: default.conf
          name: mms5-proxy-conf
          optional: false
        name: proxy-config-map
