apiVersion: v1
kind: Service
metadata:
  name: flexo-mms-auth-service
  namespace: flexo-mms
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-flexo-mms-flexo-mms-auth-service
  sessionAffinity: None
  type: ClusterIP
