#!/usr/bin/env python3

import sys
import os.path

file_path = "mms5-layer1-service/src/main/resources/application.conf"
if os.path.exists(file_path):
    # open both files
    app_example = "mms5-layer1-service/src/main/resources/application.conf.example"
    with open(file_path,'r') as firstfile, open(file_path,'w') as secondfile:
        # read content from first file
        for line in firstfile:
                 # append content to second file
                 secondfile.write(line)


