name: Build and Deploy Docs
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          mkdir -p docs
          cp -r local/* docs/
          mkdir -p docs/flexo-mms-layer1-service
          mkdir -p docs/flexo-mms-auth-service
          mkdir -p docs/flexo-mms-store-service
          chmod -R 755 submodules/
          rm .gitignore
          cp -r submodules/flexo-mms-layer1-service/docs/* docs/flexo-mms-layer1-service/
          cp -r submodules/flexo-mms-auth-service/docs/* docs/flexo-mms-auth-service/
          cp -r submodules/flexo-mms-store-service/docs/* docs/flexo-mms-store-service/
      - run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@noreply.github.com"
          git push origin --delete build/docs
          git checkout -b build/docs
          git add docs/
          git commit -m 'build: docs'
          git push -u origin build/docs

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     add: docs
      #     fetch: true
      #     message: 'docs: build'
      #     new_branch: build/docs
      #     # pull: '--rebase --autostash'
      #     push: true

  # deploy:
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: deploy
  #       id: deploymment
  #       uses: actions/deploy-pages@v2

