name: Build and Deploy Docs
on:
  push:
    branches:
      - wip/layer1-docs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          mkdir -p docs
          cp -r local/* docs/
          mkdir -p docs/mms5-layer1-service
          chmod -R 755 submodules/
      - uses: docker://pandoc/core:3
        with:
          args: "submodules/mms5-layer1-service/README.md -t rst -o docs/mms5-layer1-service/index.rst"
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout build/docs
          git add docs
          git commit -m 'docs: actions build'
          git push
  # deploy:
  #   needs: build
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: deploy
  #       id: deploymment
  #       uses: actions/deploy-pages@v2

